### ISSUE TITLE
Where is the implementation of BookitInitialize?

### ISSUE THREAD

**Issue by subvert0r** [ldpreload/BlackLotus#3]
Why is BookitInitialize missing?

**Comment by ldpreload** [comment]
BootInitialize is not required at all. UEFI driver is loaded on-the-fly.

**Comment by bytesundso** [comment]
lmao

**Comment by ldpreload** [comment]
You're being annoying. It's clear that not all the source code is public, and I'm deliberately avoiding your question. I suspect you're the same arrogant person from the HTB Discord. Stop acting like a genius 1337 elite h4x0r  and learn some humility.
On Jun 28, 2024 at 7:25 AM, subvert0r ***@***.***> wrote:

BootInitialize is not required at all. UEFI driver is loaded on-the-fly.
Are you stupid? No it doesn't get loaded on the fly lmao
I feel like you just stole this from the author (or was dumb enough to buy it without knowing how it works) and couldnt get it to work so you shared it here lol.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

-- 
Sent with https://mailfence.com  
Secure and private email
